psmportal/Controllers/lecturerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using psmportal.Models;

namespace psmportal.Controllers
{

    public class lecturerController : Controller
    {
        private db_psmportalEntities1 db = new db_psmportalEntities1();

        // GET: lecturer
        public ActionResult Index()
        {
            var tb_lecturer = db.tb_lecturer.Include(t => t.tb_domain).Include(t => t.tb_program).Include(t => t.tb_sv);

            // Get the list of domains for the dropdown
            var domainList = db.tb_domain.ToList();
            ViewBag.DomainList = new SelectList(domainList, "DomainID", "DomainName");

            return View(tb_lecturer.ToList());
        }


        [HttpPost]
        public ActionResult AssignDomain(string lecturerIC, int domainSelect)
        {
            var lecturer = db.tb_lecturer.Find(lecturerIC);
            if (lecturer != null)
            {
                lecturer.Domain = domainSelect;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        // GET: lecturer/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_lecturer tb_lecturer = db.tb_lecturer.Find(id);
            if (tb_lecturer == null)
            {
                return HttpNotFound();
            }
            return View(tb_lecturer);
        }

        // GET: lecturer/Create
        public ActionResult Create()
        {
            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName");
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName");
            ViewBag.IC = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC");
            return View();
        }

        // POST: lecturer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IC,Name,ProgramCode,Domain,Email,MobileNo")] tb_lecturer tb_lecturer, string MobileNo, bool isCommittee)
        {
            if (ModelState.IsValid)
            {
                // Insert the user information in tb_user table
                var user = new tb_user
                {
                    IC = tb_lecturer.IC,
                    Password = Crypto.HashPassword(MobileNo), // Hash the password
                    Role = isCommittee ? 2 : 4 // Set role based on the value of isCommittee
                };
                db.tb_user.Add(user);
                db.SaveChanges();

                // Insert the lecturer information in tb_lecturer table
                db.tb_lecturer.Add(tb_lecturer);
                db.SaveChanges();

                if (isCommittee)
                {
                    // Insert the committee member information in tb_committee table
                    var committee = new tb_committee
                    {
                        IC = tb_lecturer.IC
                    };
                    db.tb_committee.Add(committee);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            // If there are validation errors, debug and inspect the ModelState.Values collection
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    // Examine the error and related properties to identify the specific validation issue
                    var errorMessage = error.ErrorMessage;
                }
            }

            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName", tb_lecturer.Domain);
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName", tb_lecturer.ProgramCode);
            ViewBag.IC = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC", tb_lecturer.IC);
            return View(tb_lecturer);
        }




        // GET: lecturer/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            tb_lecturer tb_lecturer = db.tb_lecturer.Find(id);
            if (tb_lecturer == null)
            {
                return HttpNotFound();
            }

            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName", tb_lecturer.Domain);
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName", tb_lecturer.ProgramCode);
            ViewBag.IC = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC", tb_lecturer.IC);

            // Retrieve the user's role from the tb_user table
            var userRole = db.tb_user.SingleOrDefault(u => u.IC == tb_lecturer.IC)?.Role;

            // Pass the user's role to the view
            ViewBag.UserRole = userRole;

            return View(tb_lecturer);
        }


        // POST: lecturer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IC,Name,ProgramCode,Domain,Email,MobileNo")] tb_lecturer tb_lecturer, string MobileNo, bool isCommittee)
        {
            if (ModelState.IsValid)
            {
                // Update the lecturer information in tb_lecturer table
                db.Entry(tb_lecturer).State = EntityState.Modified;
                db.SaveChanges();

                // Get the user associated with the lecturer
                tb_user user = db.tb_user.FirstOrDefault(u => u.IC == tb_lecturer.IC);
                if (user != null)
                {
                    // Update the user's role based on the isCommittee flag
                    user.Role = isCommittee ? 2 : 4; // Set role based on the value of isCommittee
                    db.SaveChanges();
                }

                if (isCommittee)
                {
                    // Check if the lecturer is already a committee member
                    var committee = db.tb_committee.FirstOrDefault(c => c.IC == tb_lecturer.IC);
                    if (committee == null)
                    {
                        // Insert the committee member information in tb_committee table
                        committee = new tb_committee
                        {
                            IC = tb_lecturer.IC
                        };
                        db.tb_committee.Add(committee);
                        db.SaveChanges();
                    }
                }
                else
                {
                    // Check if the lecturer is a committee member and remove the entry if exists
                    var committee = db.tb_committee.FirstOrDefault(c => c.IC == tb_lecturer.IC);
                    if (committee != null)
                    {
                        db.tb_committee.Remove(committee);
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName", tb_lecturer.Domain);
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName", tb_lecturer.ProgramCode);
            ViewBag.IC = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC", tb_lecturer.IC);

            // Add isCommittee value to ViewBag to maintain the switch state
            ViewBag.IsCommittee = isCommittee;

            return View(tb_lecturer);
        }



        // GET: lecturer/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_lecturer tb_lecturer = db.tb_lecturer.Find(id);
            if (tb_lecturer == null)
            {
                return HttpNotFound();
            }
            return View(tb_lecturer);
        }

        // POST: lecturer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_lecturer tb_lecturer = db.tb_lecturer.Find(id);

            // Remove the lecturer from tb_lecturer table
            db.tb_lecturer.Remove(tb_lecturer);

            // Find and remove the corresponding user from tb_user table
            tb_user user = db.tb_user.Find(id);
            db.tb_user.Remove(user);

            db.SaveChanges();

            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

psmportal/Views/lecturer/Create.cshtml
@model psmportal.Models.tb_lecturer

@{
    ViewBag.Title = "Create";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        PSM Portal
    </title>
</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    @Html.Partial("_SideNavbar")
    <main class="main-content position-relative border-radius-lg ">
        @Html.Partial("_TopNavbar")

        <div class="container-fluid py-4">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header pb-0">
                                <div class="d-flex align-items-center">
                                    <h3 class="mb-0">Create New Lecturer</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="text-uppercase text-sm">Lecturer Information</p>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" name="isCommittee" value="true">
                                            <label class="form-check-label" for="flexSwitchCheckDefault">Committee</label>
                                            <input type="hidden" name="isCommittee" value="false">
                                        </div>

                                        <div class="form-group">
                                            <label for="example-text-input" class="form-control-label">Identification/Passport No.</label>
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.IC, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.IC, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Domain</label>
                                        <div class="col-md-6">
                                            @Html.DropDownList("Domain", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Domain, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Full Name</label>
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        @Html.DropDownList("ProgramCode", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ProgramCode, "", new { @class = "text-danger" })
                                    </div>

                                </div>
                                <hr class="horizontal dark">
                                <p class="text-uppercase text-sm">Contact Information</p>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Mobile No.</label>
                                        @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Email</label>
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
                @Html.Partial("_Footer")
            </div>
    </main>
</body>

</html>

psmportal/Views/lecturer/Delete.cshtml
@model psmportal.Models.tb_lecturer

@{
    ViewBag.Title = "Delete";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        PSM Portal
    </title>
</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    @Html.Partial("_SideNavbar")
    <main class="main-content position-relative border-radius-lg ">
        @Html.Partial("_TopNavbar")

        <div class="container-fluid py-4">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header pb-0">
                                <div class="d-flex align-items-center">
                                    <h3 class="mb-0">Delete Lecturer</h3>
                                </div>
                            </div>

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="card-body">
                                <p class="text-uppercase text-sm">Lecturer Information</p>
                                <div class="row">
                                    @Html.HiddenFor(model => model.IC)
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="example-text-input" class="form-control-label">Full Name</label>
                                            @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="example-text-input" class="form-control-label">Domain</label>
                                            <div class="col-md-10">
                                                @Html.DisplayFor(model => model.tb_domain.DomainName, new { htmlAttributes = new { @class = "form-control" } })
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Programme Code</label>
                                        <div class="col-md-10">
                                            @Html.DisplayFor(model => model.ProgramCode, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>

                                    </div>
                                </div>
                                <hr class="horizontal dark">
                                <p class="text-uppercase text-sm">Contact Information</p>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="example-text-input" class="form-control-label">Mobile No.</label>
                                            @Html.DisplayFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="example-text-input" class="form-control-label">Email</label>
                                                @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Delete" class="btn btn-danger" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            @Html.Partial("_Footer")
        </div>
    </main>
</body>

</html>

psmportal/Views/lecturer/Index.cshtml
@model IEnumerable<psmportal.Models.tb_lecturer>

@{
    ViewBag.Title = "Index";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        PSM Portal
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    @Html.Partial("_SideNavbar")
    <main class="main-content position-relative border-radius-lg ">
        @Html.Partial("_TopNavbar")
        <div class="container-fluid py-4">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4">
                        <div class="card-header pb-0">
                            <div class="d-flex align-items-center">
                                <h4 class="mb-0">Lecturer List</h4>
                                @if (Session["Role"] != null && Session["Role"].ToString() == "1")
                                {
                                    <button class="btn btn-icon btn-3 btn bg-gradient-secondary ms-auto" type="button">
                                        <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                        <span class="btn-inner--text">
                                            @Html.ActionLink("Create New", "Create")
                                        </span>
                                    </button>
                                }
                            </div>
                        </div>
                        <div class="card-body px-0 pt-0 pb-2">
                            <div class="table-responsive p-0">
                                <table class="table align-items-center mb-0">
                                    <thead>
                                        <tr>
                                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Name</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Mobile No</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Domain</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Programme</th>
                                            <th class="text-secondary opacity-7"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    <div class="d-flex px-2 py-1">
                                                        <div>
                                                            <img src="~/Content/assets/img/team-2.jpg" class="avatar avatar-sm me-3" alt="user1">
                                                        </div>
                                                        <div class="d-flex flex-column justify-content-center">
                                                            <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.Name)</h6>
                                                            <p class="text-xs text-secondary mb-0">@Html.DisplayFor(modelItem => item.Email)</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.MobileNo)</p>
                                                </td>
                                                <td class="align-middle text-center text-sm">
                                                    @if (item.tb_domain != null)
                                                    {
                                                        <span class="badge badge-sm @(item.tb_domain.DomainID == 1 ? "bg-gradient-success" : item.tb_domain.DomainID == 2 ? "bg-gradient-info" : "")">
                                                            @Html.DisplayFor(modelItem => item.tb_domain.DomainName)
                                                        </span>
                                                    }
                                                    else
                                                    {
                                                        <a href="#" class="badge badge-sm bg-gradient-secondary assign-domain-badge" data-lecturer-ic="@item.IC" onclick="showModal('@item.IC')">Unassigned</a>
                                                    }
                                                </td>


                                                <td class="align-middle text-center">
                                                    <span class="text-secondary text-xs font-weight-bold">@Html.DisplayFor(modelItem => item.tb_program.ProgramName)</span>
                                                </td>
                                                @if (Session["Role"] != null && Session["Role"].ToString() == "1")
                                                {
                                                    <td class="align-middle">
                                                        <a href="@Url.Action("Edit", "lecturer", new { id = item.IC })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                                            <i class="fa-sharp fa-solid fa-pencil fa-lg" style="color: #ffcb3d;"></i>
                                                        </a>
                                                        <a href="@Url.Action("Delete", "lecturer", new { id = item.IC })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Delete user">
                                                            <i class="fa-sharp fa-solid fa-trash fa-lg" style="color: #ff5252;"></i>
                                                        </a>
                                                    </td>
                                                }
                                                @if (Session["Role"] != null && Session["Role"].ToString() == "3")
                                                {
                                                    <td class="align-middle">
                                                        <a href="@Url.Action("Create", "request")" class="btn btn-dark btn-icon align-items-center btn-sm">
                                                            <span class="btn-inner--icon me-2"><i class="fa-solid fa-file-signature" style="color: #ffffff;"></i></span>
                                                            <span class="btn-inner--text">Request</span>
                                                        </a>
                                                    </td>
                                                }
                                            </tr>
                                            <!-- Modal -->
                                            <div class="modal fade" id="assignDomainModal-@item.IC" tabindex="-1" role="dialog" aria-labelledby="assignDomainModalLabel-@item.IC" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="assignDomainModalLabel-@item.IC">Assign Domain</h5>
                                                        </div>
                                                        <div class="modal-body">
                                                            <form id="assignDomainForm-@item.IC" action="@Url.Action("AssignDomain", "Lecturer")" method="post">
                                                                @Html.Hidden("lecturerIC", item.IC)
                                                                <div class="form-group">
                                                                    <label for="domainSelect">Domain:</label>
                                                                    @Html.DropDownList("domainSelect", ViewBag.DomainList as SelectList, "-- Select Domain --", new { @class = "form-select" })
                                                                </div>
                                                            </form>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                            <button type="submit" form="assignDomainForm-@item.IC" class="btn btn-primary">Save Changes</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- End Modal -->
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.Partial("_Footer")
    </main>
</body>

</html>
<script>
    function showModal(lecturerIC) {
        var modalId = "#assignDomainModal-" + lecturerIC;
        $(modalId).modal('show');
    }
</script>