psmportal/Controllers/programController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using psmportal.Models;

namespace psmportal.Controllers
{

    public class programController : Controller
    {
        private     db_psmportalEntities1 db = new db_psmportalEntities1();

        // GET: program
        public ActionResult Index()
        {
            return View(db.tb_program.ToList());
        }

        // GET: program/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_program tb_program = db.tb_program.Find(id);
            if (tb_program == null)
            {
                return HttpNotFound();
            }
            return View(tb_program);
        }

        // GET: program/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: program/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProgramID,ProgramName")] tb_program tb_program)
        {
            if (ModelState.IsValid)
            {
                db.tb_program.Add(tb_program);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tb_program);
        }

        // GET: program/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_program tb_program = db.tb_program.Find(id);
            if (tb_program == null)
            {
                return HttpNotFound();
            }
            return View(tb_program);
        }

        // POST: program/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProgramID,ProgramName")] tb_program tb_program)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_program).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tb_program);
        }

        // GET: program/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_program tb_program = db.tb_program.Find(id);
            if (tb_program == null)
            {
                return HttpNotFound();
            }
            return View(tb_program);
        }

        // POST: program/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_program tb_program = db.tb_program.Find(id);
            db.tb_program.Remove(tb_program);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

psmportal/Controllers/svController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using psmportal.Models;
using SelectPdf;
using System.IO;


namespace psmportal.Controllers
{

    public class svController : Controller
    {
        private db_psmportalEntities1 db = new db_psmportalEntities1();

        // GET: sv
        public ActionResult Index()
        {
            var tb_sv = db.tb_sv.Include(t => t.tb_lecturer);
            return View(tb_sv.ToList());
        }

        // GET: sv/Details/5
        public ActionResult Details()
        {
            var tb_student = db.tb_student.FirstOrDefault(); // Assuming there is only one tb_student record

            if (tb_student == null)
            {
                return HttpNotFound();
            }

            ViewBag.HasSupervisor = string.IsNullOrEmpty(tb_student.Supervisor);

            return View(tb_student);
        }



        // GET: sv/Create
        public ActionResult Create()
        {
            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name");
            return View();
        }

        // POST: sv/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SupervisorIC,OwnedStudentIC")] tb_sv tb_sv)
        {
            if (ModelState.IsValid)
            {
                db.tb_sv.Add(tb_sv);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", tb_sv.SupervisorIC);
            return View(tb_sv);
        }

        // GET: sv/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_sv tb_sv = db.tb_sv.Find(id);
            if (tb_sv == null)
            {
                return HttpNotFound();
            }
            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", tb_sv.SupervisorIC);
            return View(tb_sv);
        }

        // POST: sv/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SupervisorIC,OwnedStudentIC")] tb_sv tb_sv)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_sv).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", tb_sv.SupervisorIC);
            return View(tb_sv);
        }

        // GET: sv/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_sv tb_sv = db.tb_sv.Find(id);
            if (tb_sv == null)
            {
                return HttpNotFound();
            }
            return View(tb_sv);
        }

        // POST: sv/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_sv tb_sv = db.tb_sv.Find(id);
            db.tb_sv.Remove(tb_sv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GenerateAgreement()
        {
            var tb_student = db.tb_student.FirstOrDefault(); // Assuming there is only one tb_student record
            var tb_sv = db.tb_sv.Include(t => t.tb_lecturer).FirstOrDefault(); // Assuming there is only one tb_sv record

            string studentName = tb_student != null ? tb_student.Name : "";
            string supervisorName = tb_sv != null && tb_sv.tb_lecturer != null ? tb_sv.tb_lecturer.Name : "";

            // Generate the PDF
            PdfDocument doc = new PdfDocument();
            PdfPage page = doc.AddPage();
            HtmlToPdf converter = new HtmlToPdf();
            string htmlString = "<html><body>" +
             "<img src=\"https://comp.utm.my/psm/wp-content/blogs.dir/2566/files/2020/01/PSM-logo.png\">" +
             "<h1>Student and Supervisor Agreement</h1>" +
             "<p>Student: " + studentName + "</p>" +
             "<p>Matrics No.: " + (tb_student != null ? tb_student.MatricNo : "") + "</p>" +
             "<p>Supervisor: " + supervisorName + "</p>" +
             "<p>IC: " + tb_sv.SupervisorIC + "</p>" +
             "<p>This agreement is made between " + studentName + " (hereinafter referred to as \"the Student\") " +
             "and " + supervisorName + " (hereinafter referred to as \"the Supervisor\") for the purpose of supervising " +
             "the student's Final Year Project (FYP).</p>" +
             "<h2>Responsibilities of the Student:</h2>" +
             "<ol>" +
             "<li>The Student agrees to actively participate in the [project/thesis/dissertation] under the guidance of the Supervisor.</li>" +
             "<li>The Student will meet regularly with the Supervisor to discuss the progress, challenges, and any necessary modifications to the project.</li>" +
             "<li>The Student will adhere to the academic and ethical guidelines set by the institution and maintain the highest standards of research integrity.</li>" +
             "<li>The Student will submit progress reports, drafts, and final deliverables as per the agreed-upon timeline.</li>" +
             "</ol>" +
             "<h2>Responsibilities of the Supervisor:</h2>" +
             "<ol>" +
             "<li>The Supervisor agrees to provide guidance and support to the Student throughout the duration of the [project/thesis/dissertation].</li>" +
             "<li>The Supervisor will meet with the Student on a regular basis to provide feedback, suggestions, and direction for the project.</li>" +
             "<li>The Supervisor will assist the Student in identifying relevant resources, references, and research methodologies.</li>" +
             "<li>The Supervisor will review and provide constructive feedback on the drafts and final deliverables submitted by the Student.</li>" +
             "</ol>" +
             "<h2>Duration and Termination:</h2>" +
             "<ol>" +
             "<li>This agreement will be in effect from [Start Date] to [End Date].</li>" +
             "<li>Either party has the right to terminate this agreement by providing written notice to the other party.</li>" +
             "<li>In case of termination, the Student may be required to find an alternate Supervisor or adjust the scope of the project as per the institution's guidelines.</li>" +
             "</ol>" +
             "<h2>Confidentiality and Intellectual Property:</h2>" +
             "<ol>" +
             "<li>Both the Student and the Supervisor agree to maintain the confidentiality of any sensitive information shared during the course of the project.</li>" +
             "<li>Any intellectual property rights arising from the project will be discussed and agreed upon separately, as per the institution's policies and guidelines.</li>" +
             "</ol>" +
             "</body></html>";

            PdfDocument pdf = converter.ConvertHtmlString(htmlString);
            MemoryStream stream = new MemoryStream();
            pdf.Save(stream);
            pdf.Close();

            // Return the PDF file
            stream.Position = 0;
            return File(stream, "application/pdf", "Agreement.pdf");
        }

    }
}

psmportal/Views/Shared/_Footer.cshtml
<footer class="footer pt-3  ">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
                <div class="copyright text-center text-sm text-muted text-lg-start">
                    ©
                    <script>document.write(new Date().getFullYear())</script>,
                    made with <i class="fa fa-heart"></i> by
                    <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Izzah Mardhiah</a>
                </div>
            </div>
        </div>
    </div>
</footer>

psmportal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="apple-touch-icon" sizes="76x76" href="~/Content/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/Content/assets/img/favicon.png">

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <!-- Nucleo Icons -->
    <link href="~/Content/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/Content/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="~/Content/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link id="pagestyle" href="~/Content/assets/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />

</head>
<body>

    @RenderBody()

    <div class="fixed-plugin">
        <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
            <i class="fa fa-cog py-2"> </i>
        </a>
        <div class="card shadow-lg">
            <div class="card-header pb-0 pt-3 ">
                <div class="float-start">
                    <h5 class="mt-3 mb-0">Argon Configurator</h5>
                    <p>See our dashboard options.</p>
                </div>
                <div class="float-end mt-4">
                    <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
                        <i class="fa fa-close"></i>
                    </button>
                </div>
                <!-- End Toggle Button -->
            </div>
            <hr class="horizontal dark my-1">
            <div class="card-body pt-sm-3 pt-0 overflow-auto">
                <!-- Sidebar Backgrounds -->
                <div>
                    <h6 class="mb-0">Sidebar Colors</h6>
                </div>
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <div class="badge-colors my-2 text-start">
                        <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
                    </div>
                </a>
                <!-- Sidenav Type -->
                <div class="mt-3">
                    <h6 class="mb-0">Sidenav Type</h6>
                    <p class="text-sm">Choose between 2 different sidenav types.</p>
                </div>
                <div class="d-flex">
                    <button class="btn bg-gradient-primary w-100 px-3 mb-2 active me-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
                    <button class="btn bg-gradient-primary w-100 px-3 mb-2" data-class="bg-default" onclick="sidebarType(this)">Dark</button>
                </div>
                <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
                <!-- Navbar Fixed -->
                <div class="d-flex my-3">
                    <h6 class="mb-0">Navbar Fixed</h6>
                    <div class="form-check form-switch ps-0 ms-auto my-auto">
                        <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
                    </div>
                </div>
                <hr class="horizontal dark my-sm-4">
                <div class="mt-2 mb-5 d-flex">
                    <h6 class="mb-0">Light / Dark</h6>
                    <div class="form-check form-switch ps-0 ms-auto my-auto">
                        <input class="form-check-input mt-1 ms-auto" type="checkbox" id="dark-version" onclick="darkMode(this)">
                    </div>
                </div>
                <a class="btn bg-gradient-dark w-100" href="https://www.creative-tim.com/product/argon-dashboard">Free Download</a>
                <a class="btn btn-outline-dark w-100" href="https://www.creative-tim.com/learning-lab/bootstrap/license/argon-dashboard">View documentation</a>
                <div class="w-100 text-center">
                    <a class="github-button" href="https://github.com/creativetimofficial/argon-dashboard" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star creativetimofficial/argon-dashboard on GitHub">Star</a>
                    <h6 class="mt-3">Thank you for sharing!</h6>
                    <a href="https://twitter.com/intent/tweet?text=Check%20Argon%20Dashboard%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fargon-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
                        <i class="fab fa-twitter me-1" aria-hidden="true"></i> Tweet
                    </a>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.creative-tim.com/product/argon-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
                        <i class="fab fa-facebook-square me-1" aria-hidden="true"></i> Share
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="~/Content/assets/js/core/popper.min.js"></script>
    <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/Content/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="~/Content/assets/js/plugins/chartjs.min.js"></script>
    <script>
        var ctx1 = document.getElementById("chart-line").getContext("2d");

        var gradientStroke1 = ctx1.createLinearGradient(0, 230, 0, 50);

        gradientStroke1.addColorStop(1, 'rgba(94, 114, 228, 0.2)');
        gradientStroke1.addColorStop(0.2, 'rgba(94, 114, 228, 0.0)');
        gradientStroke1.addColorStop(0, 'rgba(94, 114, 228, 0)');
        new Chart(ctx1, {
            type: "line",
            data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0.4,
                    borderWidth: 0,
                    pointRadius: 0,
                    borderColor: "#5e72e4",
                    backgroundColor: gradientStroke1,
                    borderWidth: 3,
                    fill: true,
                    data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
                    maxBarThickness: 6

                }],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            padding: 10,
                            color: '#fbfbfb',
                            font: {
                                size: 11,
                                family: "Open Sans",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: false,
                            drawOnChartArea: false,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            color: '#ccc',
                            padding: 20,
                            font: {
                                size: 11,
                                family: "Open Sans",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });</script>
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }</script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/Content/assets/js/argon-dashboard.min.js?v=2.0.4"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

psmportal/Views/Shared/_SideNavbar.cshtml
<aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/Content/assets/img/PSM-logo.png" class="navbar-brand-img h-100" alt="main_logo">
        </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Home")">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "lecturer")">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Lecturer List</span>
                </a>
            </li>

            @if (Session["Role"] != null && Session["Role"].ToString() == "2") // committee
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "student")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Student List</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "request")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Supervisor Request</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "proposal")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Proposal</span>
                    </a>
                </li>
            }

            @if (Session["Role"] != null && Session["Role"].ToString() == "3") //student
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Details", "sv")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-app text-info text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Supervisor</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "proposal")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Proposal</span>
                    </a>
                </li>
            }
            @if (Session["Role"] != null && Session["Role"].ToString() == "1") //admin
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "program")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-app text-info text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Program List</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "committee")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-app text-info text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Committee List</span>
                    </a>
                </li>
            }
            @if (Session["Role"] != null && Session["Role"].ToString() == "4") // lecturer/supervisor/evaluator
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "proposal")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Proposal</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("IndexEvaluator", "Proposal")"> @*evaluator*@
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Student List</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "student")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Student List</span>
                    </a>
                </li>
            }
            <li class="nav-item mt-3">
                <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Account pages</h6>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="~/Content/pages/profile.html">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="~/Content/pages/sign-up.html">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="ni ni-collection text-info text-sm opacity-10"></i>
                    </div>
                    <span class="nav-link-text ms-1">Register User</span>
                </a>
            </li>
        </ul>
    </div>
</aside>