psmportal/Controllers/requestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using psmportal.Models;
using psmportal.Models.ViewModels;

namespace psmportal.Controllers
{

    public class requestController : Controller
    {
        private db_psmportalEntities1 db = new db_psmportalEntities1();

        // GET: request
        public ActionResult Index()
        {
            var tb_request = db.tb_request.Include(t => t.tb_lecturer).Include(t => t.tb_student);
            return View(tb_request.ToList());
        }

        // GET: request/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_request tb_request = db.tb_request.Find(id);
            if (tb_request == null)
            {
                return HttpNotFound();
            }
            return View(tb_request);
        }

        // GET: request/Create
        // GET: request/Create
        public ActionResult Create()
        {
            var viewModel = new RequestCreateViewModel
            {
                Request = new tb_request
                {
                    // Set the default values for the properties
                    Status = 1,
                },
                Lecturers = db.tb_lecturer.ToList()
            };

            return View(viewModel);
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: request/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RequestCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the StudentIC value from the hidden field
                viewModel.Request.StudentIC = viewModel.Request.StudentIC;

                // Set the default value for Status
                viewModel.Request.Status = 1;

                db.tb_request.Add(viewModel.Request);
                db.SaveChanges();
                return RedirectToAction("Index", "sv");
            }

            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", viewModel.Request.SupervisorIC);
            ViewBag.StudentIC = new SelectList(db.tb_student, "IC", "MatricNo", viewModel.Request.StudentIC);

            // Pass the view model to the view
            return View(viewModel);
        }


        // POST: request/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RequestID,StudentIC,SupervisorIC,Notes")] tb_request tb_request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", tb_request.SupervisorIC);
            ViewBag.StudentIC = new SelectList(db.tb_student, "IC", "MatricNo", tb_request.StudentIC);
            return View(tb_request);
        }

        // GET: request/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_request tb_request = db.tb_request.Find(id);
            if (tb_request == null)
            {
                return HttpNotFound();
            }
            return View(tb_request);
        }

        // POST: request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_request tb_request = db.tb_request.Find(id);
            db.tb_request.Remove(tb_request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult UpdateRequestStatus(int[] requestIds, int status)
        {
            if (requestIds != null && requestIds.Length > 0)
            {
                var requestsToUpdate = db.tb_request.Include("tb_student").Where(r => requestIds.Contains(r.RequestID));

                foreach (var request in requestsToUpdate)
                {
                    request.Status = status;

                    if (status == 2)
                    {
                        // Update Supervisor column in tb_student
                        request.tb_student.Supervisor = request.SupervisorIC;

                        // Insert a new row in tb_sv
                        tb_sv newSvRow = new tb_sv()
                        {
                            SupervisorIC = request.SupervisorIC,
                            OwnedStudentIC = request.StudentIC
                        };

                        db.tb_sv.Add(newSvRow);
                    }
                }

                db.SaveChanges();

                // Create a success message
                string message = (status == 2) ? "Requests approved successfully." : "Requests rejected successfully.";

                return Json(new { success = true, message = message });
            }

            return Json(new { success = false, message = "No requests selected." });
        }


    }
}

psmportal/Controllers/svController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using psmportal.Models;
using SelectPdf;
using System.IO;


namespace psmportal.Controllers
{

    public class svController : Controller
    {
        private db_psmportalEntities1 db = new db_psmportalEntities1();

        // GET: sv
        public ActionResult Index()
        {
            var tb_sv = db.tb_sv.Include(t => t.tb_lecturer);
            return View(tb_sv.ToList());
        }

        // GET: sv/Details/5
        public ActionResult Details()
        {
            var tb_student = db.tb_student.FirstOrDefault(); // Assuming there is only one tb_student record

            if (tb_student == null)
            {
                return HttpNotFound();
            }

            ViewBag.HasSupervisor = string.IsNullOrEmpty(tb_student.Supervisor);

            return View(tb_student);
        }



        // GET: sv/Create
        public ActionResult Create()
        {
            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name");
            return View();
        }

        // POST: sv/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SupervisorIC,OwnedStudentIC")] tb_sv tb_sv)
        {
            if (ModelState.IsValid)
            {
                db.tb_sv.Add(tb_sv);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", tb_sv.SupervisorIC);
            return View(tb_sv);
        }

        // GET: sv/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_sv tb_sv = db.tb_sv.Find(id);
            if (tb_sv == null)
            {
                return HttpNotFound();
            }
            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", tb_sv.SupervisorIC);
            return View(tb_sv);
        }

        // POST: sv/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SupervisorIC,OwnedStudentIC")] tb_sv tb_sv)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_sv).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SupervisorIC = new SelectList(db.tb_lecturer, "IC", "Name", tb_sv.SupervisorIC);
            return View(tb_sv);
        }

        // GET: sv/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_sv tb_sv = db.tb_sv.Find(id);
            if (tb_sv == null)
            {
                return HttpNotFound();
            }
            return View(tb_sv);
        }

        // POST: sv/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_sv tb_sv = db.tb_sv.Find(id);
            db.tb_sv.Remove(tb_sv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GenerateAgreement()
        {
            var tb_student = db.tb_student.FirstOrDefault(); // Assuming there is only one tb_student record
            var tb_sv = db.tb_sv.Include(t => t.tb_lecturer).FirstOrDefault(); // Assuming there is only one tb_sv record

            string studentName = tb_student != null ? tb_student.Name : "";
            string supervisorName = tb_sv != null && tb_sv.tb_lecturer != null ? tb_sv.tb_lecturer.Name : "";

            // Generate the PDF
            PdfDocument doc = new PdfDocument();
            PdfPage page = doc.AddPage();
            HtmlToPdf converter = new HtmlToPdf();
            string htmlString = "<html><body>" +
             "<img src=\"https://comp.utm.my/psm/wp-content/blogs.dir/2566/files/2020/01/PSM-logo.png\">" +
             "<h1>Student and Supervisor Agreement</h1>" +
             "<p>Student: " + studentName + "</p>" +
             "<p>Matrics No.: " + (tb_student != null ? tb_student.MatricNo : "") + "</p>" +
             "<p>Supervisor: " + supervisorName + "</p>" +
             "<p>IC: " + tb_sv.SupervisorIC + "</p>" +
             "<p>This agreement is made between " + studentName + " (hereinafter referred to as \"the Student\") " +
             "and " + supervisorName + " (hereinafter referred to as \"the Supervisor\") for the purpose of supervising " +
             "the student's Final Year Project (FYP).</p>" +
             "<h2>Responsibilities of the Student:</h2>" +
             "<ol>" +
             "<li>The Student agrees to actively participate in the [project/thesis/dissertation] under the guidance of the Supervisor.</li>" +
             "<li>The Student will meet regularly with the Supervisor to discuss the progress, challenges, and any necessary modifications to the project.</li>" +
             "<li>The Student will adhere to the academic and ethical guidelines set by the institution and maintain the highest standards of research integrity.</li>" +
             "<li>The Student will submit progress reports, drafts, and final deliverables as per the agreed-upon timeline.</li>" +
             "</ol>" +
             "<h2>Responsibilities of the Supervisor:</h2>" +
             "<ol>" +
             "<li>The Supervisor agrees to provide guidance and support to the Student throughout the duration of the [project/thesis/dissertation].</li>" +
             "<li>The Supervisor will meet with the Student on a regular basis to provide feedback, suggestions, and direction for the project.</li>" +
             "<li>The Supervisor will assist the Student in identifying relevant resources, references, and research methodologies.</li>" +
             "<li>The Supervisor will review and provide constructive feedback on the drafts and final deliverables submitted by the Student.</li>" +
             "</ol>" +
             "<h2>Duration and Termination:</h2>" +
             "<ol>" +
             "<li>This agreement will be in effect from [Start Date] to [End Date].</li>" +
             "<li>Either party has the right to terminate this agreement by providing written notice to the other party.</li>" +
             "<li>In case of termination, the Student may be required to find an alternate Supervisor or adjust the scope of the project as per the institution's guidelines.</li>" +
             "</ol>" +
             "<h2>Confidentiality and Intellectual Property:</h2>" +
             "<ol>" +
             "<li>Both the Student and the Supervisor agree to maintain the confidentiality of any sensitive information shared during the course of the project.</li>" +
             "<li>Any intellectual property rights arising from the project will be discussed and agreed upon separately, as per the institution's policies and guidelines.</li>" +
             "</ol>" +
             "</body></html>";

            PdfDocument pdf = converter.ConvertHtmlString(htmlString);
            MemoryStream stream = new MemoryStream();
            pdf.Save(stream);
            pdf.Close();

            // Return the PDF file
            stream.Position = 0;
            return File(stream, "application/pdf", "Agreement.pdf");
        }

    }
}

psmportal/Views/sv/Create.cshtml
@model psmportal.Models.tb_sv

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tb_sv</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SupervisorIC, "SupervisorIC", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupervisorIC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupervisorIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnedStudentIC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnedStudentIC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnedStudentIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

psmportal/Views/sv/Delete.cshtml
@model psmportal.Models.tb_sv

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tb_sv</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OwnedStudentIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnedStudentIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_lecturer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_lecturer.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

psmportal/Views/sv/Details.cshtml
@model psmportal.Models.tb_student

@{
    ViewBag.Title = "Details";
}

@{
    ViewBag.Title = "Index";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        PSM Portal
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    @Html.Partial("_SideNavbar")
    <main class="main-content position-relative border-radius-lg ">
        @Html.Partial("_TopNavbar")
        <div class="container-fluid py-4">
            <div class="row">
                @if (string.IsNullOrEmpty(Model.Supervisor))
                {
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body text-center">
                                <h5 class="card-title">No Supervisor</h5>
                                <p class="card-text">You don't have a supervisor assigned yet.</p>
                                <a href="@Url.Action("Create", "request")" class="btn btn-primary">Request Supervisor</a>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-md-6">
                        <div class="card card-profile">
                            <img src="~/Content/assets/img/utm.jpg" alt="Image placeholder" class="card-img-top">
                            <div class="row justify-content-center">
                                <div class="col-4 col-lg-4 order-lg-2">
                                    <div class="mt-n4 mt-lg-n6 mb-4 mb-lg-0">
                                        <a href="javascript:;">
                                            <img src="~/Content/assets/img/team-2.jpg" class="rounded-circle img-fluid border border-2 border-white">
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="card-header text-center border-0 pt-0 pt-lg-2 pb-4 pb-lg-3">
                                <div class="d-flex justify-content-between">
                                    <a href="@Url.Action("GenerateAgreement", "sv")" class="btn btn-sm btn-info mb-0 d-none d-lg-block" target="_blank">Agreement</a>
                                    <a href="javascript:;" class="btn btn-sm btn-dark float-right mb-0 d-none d-lg-block">Message</a>
                                </div>
                            </div>
                            <div class="card-body pt-0">
                                <div class="text-center mt-4">
                                    <div>
                                        <i class="ni education_hat mr-2"></i>Supervisor
                                    </div>
                                    <h5>
                                        @Html.DisplayFor(model => model.tb_sv.tb_lecturer.Name)
                                    </h5>
                                    <div class="h6 font-weight-300">
                                        @Html.DisplayFor(model => model.tb_sv.tb_lecturer.ProgramCode)
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        @Html.Partial("_Footer")
    </main>
</body>

</html>

psmportal/Views/sv/Edit.cshtml
@model psmportal.Models.tb_sv

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tb_sv</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SupervisorIC)

        <div class="form-group">
            @Html.LabelFor(model => model.OwnedStudentIC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnedStudentIC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnedStudentIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

psmportal/Views/sv/Index.cshtml
@model IEnumerable<psmportal.Models.tb_sv>

@{
    ViewBag.Title = "Index";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        PSM Portal
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    @Html.Partial("_SideNavbar")
    <main class="main-content position-relative border-radius-lg ">
        @Html.Partial("_TopNavbar")
        <div class="container-fluid py-4">
            <div class="row">
                @if (!Model.Any())
                {
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body text-center">
                                <h5 class="card-title">No Supervisor</h5>
                                <p class="card-text">You don't have a supervisor assigned yet.</p>
                                <a href="@Url.Action("Create", "request")" class="btn btn-primary">Request Supervisor</a>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-md-6">
                        <div class="card card-profile">
                            <img src="~/Content/assets/img/utm.jpg" alt="Image placeholder" class="card-img-top">
                            <div class="row justify-content-center">
                                <div class="col-4 col-lg-4 order-lg-2">
                                    <div class="mt-n4 mt-lg-n6 mb-4 mb-lg-0">
                                        <a href="javascript:;">
                                            <img src="~/Content/assets/img/team-2.jpg" class="rounded-circle img-fluid border border-2 border-white">
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="card-header text-center border-0 pt-0 pt-lg-2 pb-4 pb-lg-3">
                                <div class="d-flex justify-content-between">
                                    <a href="javascript:;" class="btn btn-sm btn-info mb-0 d-none d-lg-block">Connect</a>
                                    <a href="javascript:;" class="btn btn-sm btn-info mb-0 d-block d-lg-none"><i class="ni ni-collection"></i></a>
                                    <a href="javascript:;" class="btn btn-sm btn-dark float-right mb-0 d-none d-lg-block">Message</a>
                                    <a href="javascript:;" class="btn btn-sm btn-dark float-right mb-0 d-block d-lg-none"><i class="ni ni-email-83"></i></a>
                                </div>
                            </div>
                            <div class="card-body pt-0">
                                <div class="row">
                                    <div class="col">
                                        <div class="d-flex justify-content-center">
                                            <div class="d-grid text-center">
                                                <span class="text-lg font-weight-bolder">22</span>
                                                <span class="text-sm opacity-8">Friends</span>
                                            </div>
                                            <div class="d-grid text-center mx-4">
                                                <span class="text-lg font-weight-bolder">10</span>
                                                <span class="text-sm opacity-8">Photos</span>
                                            </div>
                                            <div class="d-grid text-center">
                                                <span class="text-lg font-weight-bolder">89</span>
                                                <span class="text-sm opacity-8">Comments</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="text-center mt-4">
                                    <h5>
                                        Iqbal Tariq<span class="font-weight-light">, 35</span>
                                    </h5>
                                    <div class="h6 font-weight-300">
                                        <i class="ni location_pin mr-2"></i>Bucharest, Romania
                                    </div>
                                    <div class="h6 mt-4">
                                        <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
                                    </div>
                                    <div>
                                        <i class="ni education_hat mr-2"></i>University of Computer Science
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        @Html.Partial("_Footer")
    </main>
</body>

</html>