psmportal/Controllers/studentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using psmportal.Models;



namespace psmportal.Controllers
{

    public class studentController : Controller
    {
        private db_psmportalEntities1 db = new db_psmportalEntities1();

        // GET: student
        public ActionResult Index()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "4") // supervisor
            {
                // Get the supervisor IC from the session
                string supervisorIC = Session["IC"].ToString();

                // Store the supervisor IC in ViewBag
                ViewBag.SupervisorIC = supervisorIC;

                // Retrieve the student list owned by the supervisor
                var tb_student = db.tb_student
                    .Where(s => s.tb_sv.SupervisorIC == supervisorIC)
                    .Include(t => t.tb_domain)
                    .Include(t => t.tb_program)
                    .Include(t => t.tb_proposal)
                    .Include(t => t.tb_sv)
                    .ToList();

                return View(tb_student);
            }

            // For other roles, return an empty student list
            return View(new List<tb_student>());
        }


        // GET: student/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            return View(tb_student);
        }

        // GET: student/Create
        public ActionResult Create()
        {
            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName");
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName");
            ViewBag.ProposalID = new SelectList(db.tb_proposal, "ProposalID", "Title");
            ViewBag.Supervisor = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC");
            return View();
        }

        // POST: student/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IC,MatricNo,Name,ProgramCode,Email,MobileNo,AcademicSession,Supervisor,Agreement,Domain,ProposalID")] tb_student tb_student)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Create a new instance of tb_user and assign values
                    tb_user user = new tb_user();
                    user.IC = tb_student.IC;
                    user.Password = Crypto.HashPassword(tb_student.MobileNo); // Hash the password
                    user.Role = 3;

                    // Add the user to the context
                    db.tb_user.Add(user);

                    // Assign the user's IC to the tb_student object
                    tb_student.IC = user.IC;

                    // Add the student to tb_student
                    db.tb_student.Add(tb_student);

                    // Save changes to the database
                    db.SaveChanges();

                    return RedirectToAction("Index", "Login");
                }
                catch (DbEntityValidationException ex)
                {
                    // Handle validation errors
                    var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                    // Log or handle the error messages as needed
                    foreach (var errorMessage in errorMessages)
                    {
                        ModelState.AddModelError("", errorMessage);
                    }
                }
            }

            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName", tb_student.Domain);
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName", tb_student.ProgramCode);
            ViewBag.ProposalID = new SelectList(db.tb_proposal, "ProposalID", "Title", tb_student.ProposalID);
            ViewBag.Supervisor = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC", tb_student.Supervisor);
            return View(tb_student);
        }




        // GET: student/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName", tb_student.Domain);
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName", tb_student.ProgramCode);
            ViewBag.ProposalID = new SelectList(db.tb_proposal, "ProposalID", "Title", tb_student.ProposalID);
            ViewBag.Supervisor = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC", tb_student.Supervisor);
            return View(tb_student);
        }

        // POST: student/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IC,MatricNo,Name,ProgramCode,Email,MobileNo,AcademicSession,Supervisor,Agreement,Domain,ProposalID")] tb_student tb_student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Domain = new SelectList(db.tb_domain, "DomainID", "DomainName", tb_student.Domain);
            ViewBag.ProgramCode = new SelectList(db.tb_program, "ProgramID", "ProgramName", tb_student.ProgramCode);
            ViewBag.ProposalID = new SelectList(db.tb_proposal, "ProposalID", "Title", tb_student.ProposalID);
            ViewBag.Supervisor = new SelectList(db.tb_sv, "SupervisorIC", "OwnedStudentIC", tb_student.Supervisor);
            return View(tb_student);
        }

        // GET: student/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_student tb_student = db.tb_student.Find(id);
            if (tb_student == null)
            {
                return HttpNotFound();
            }
            return View(tb_student);
        }

        // POST: student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_student tb_student = db.tb_student.Find(id);
            db.tb_student.Remove(tb_student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

psmportal/Views/student/Create.cshtml
@model psmportal.Models.tb_student

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>
<html lang="en">

<body class="">
    <main class="main-content  mt-0">
        <div class="page-header align-items-start min-vh-50 pt-5 pb-11 m-3 border-radius-lg" style="background-image: url('https://photos.utm.my/wp-content/uploads/2021/12/DSC00090-scaled.jpg'); background-position: bottom; ">
            <span class="mask bg-gradient-dark opacity-6"></span>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5 text-center mx-auto">
                        <h3 class="text-white mb-2 mt-5">Portal Projek Sarjana Muda</h3>
                        <p class="text-lead text-white">Universiti Teknologi Malaysia</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row mt-lg-n10 mt-md-n11 mt-n10 justify-content-center">
                <div class="col-xl-7 col-lg-8 col-md-12 mx-auto">
                    <div class="card z-index-0 style="width: 900px;"">
                        <div class="card-header text-center pt-4">
                            <h4>Student Registration</h4>
                        </div>

                        <div class="card-body">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Identification No.</label>
                                        @Html.EditorFor(model => model.IC, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.IC, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Full Name</label>
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Matric No.</label>
                                        @Html.EditorFor(model => model.MatricNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.MatricNo, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Email</label>
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Mobile No.</label>
                                        @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Programme</label>
                                        @Html.DropDownList("ProgramCode", null, "-- Select Program --", htmlAttributes: new { @class = "form-select" })
                                        @Html.ValidationMessageFor(model => model.ProgramCode, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Academic Session</label>
                                        @Html.EditorFor(model => model.AcademicSession, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.AcademicSession, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        <label for="example-text-input" class="form-control-label">Domain</label>
                                        @Html.DropDownList("Domain", null, "-- Select Domain --", htmlAttributes: new { @class = "form-select" })
                                        @Html.ValidationMessageFor(model => model.Domain, "", new { @class = "text-danger" })
                                    </div>

                                </div>
                                <hr>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                                <div class="col-md-6">
                                                    <input type="submit" value="Create" class="btn btn-default" />
                                                </div>
                                        </div>
                                    </div>
                                </div>

                                }

                            </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
    <footer class="footer py-5">
        <div class="container">

            <div class="row">
                <div class="col-8 mx-auto text-center mt-1">
                    <p class="mb-0 text-secondary">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script> Universiti Teknologi Malaysia
                    </p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

psmportal/Views/student/Delete.cshtml
@model psmportal.Models.tb_student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tb_student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MatricNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatricNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcademicSession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcademicSession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agreement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agreement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_domain.DomainName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_domain.DomainName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_program.ProgramName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_program.ProgramName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_proposal.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_proposal.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_sv.OwnedStudentIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_sv.OwnedStudentIC)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

psmportal/Views/student/Details.cshtml
@model psmportal.Models.tb_student

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tb_student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MatricNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatricNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcademicSession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcademicSession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agreement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agreement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_domain.DomainName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_domain.DomainName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_program.ProgramName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_program.ProgramName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_proposal.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_proposal.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_sv.OwnedStudentIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_sv.OwnedStudentIC)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IC }) |
    @Html.ActionLink("Back to List", "Index")
</p>

psmportal/Views/student/Index.cshtml
@model IEnumerable<psmportal.Models.tb_student>

@{
    ViewBag.Title = "Index";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        PSM Portal
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    @Html.Partial("_SideNavbar")
    <main class="main-content position-relative border-radius-lg ">
        @Html.Partial("_TopNavbar")
        <div class="container-fluid py-4">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4">
                        <div class="card-header pb-0">
                            <div class="d-flex align-items-center">
                                <h4 class="mb-0">Student List</h4>
                            </div>
                        </div>
                        <div class="card-body px-0 pt-0 pb-2">
                            <div class="table-responsive p-0">
                                <table class="table align-items-center mb-0">
                                    <thead>
                                        <tr>
                                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Name</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Matric No.</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Mobile No.</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Academic Session</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Programme</th>
                                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Proposal</th>
                                            <th class="text-secondary opacity-7"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Session["Role"] != null && Session["Role"].ToString() == "2") // committee
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        <div class="d-flex px-2 py-1">
                                                            <div>
                                                                <img src="~/Content/assets/img/team-2.jpg" class="avatar avatar-sm me-3" alt="user1">
                                                            </div>
                                                            <div class="d-flex flex-column justify-content-center">
                                                                <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.Name)</h6>
                                                                <p class="text-xs text-secondary mb-0">@Html.DisplayFor(modelItem => item.Email)</p>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.MatricNo)</p>
                                                    </td>
                                                    <td>
                                                        <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.MobileNo)</p>
                                                    </td>
                                                    <td>
                                                        <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.AcademicSession)</p>
                                                    </td>
                                                    <td class="align-middle text-center">
                                                        <span class="text-secondary text-xs font-weight-bold">@Html.DisplayFor(modelItem => item.ProgramCode)</span>
                                                    </td>
                                                    <td class="align-middle text-center">
                                                        <a href="@Url.Action("Details", "proposal", new { id = item.IC })" class="btn btn-info btn-icon align-items-center btn-sm">
                                                            <span class="btn-inner--icon"><i class="fa-solid fa-file-lines" style="color: #ffffff;"></i></span>
                                                            <span class="btn-inner--text">Proposal</span>
                                                        </a>
                                                    </td>
                                                    <td class="align-middle">
                                                        <a href="@Url.Action("Edit", "student", new { id = item.IC })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                                            <i class="fa-sharp fa-solid fa-pencil fa-lg" style="color: #ffcb3d;"></i>
                                                        </a>
                                                        <a href="@Url.Action("Details", "student", new { id = item.IC })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Details user">
                                                            <i class="fa-sharp fa-solid fa-eye fa-lg" style="color: #2d5eb4;"></i>
                                                        </a>
                                                        <a href="@Url.Action("Delete", "student", new { id = item.IC })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Delete user">
                                                            <i class="fa-sharp fa-solid fa-trash fa-lg" style="color: #ff5252;"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            }
                                        }
                                        @if (Session["Role"] != null && Session["Role"].ToString() == "4") // supervisor
                                        {
                                            foreach (var item in Model.Where(x => x.tb_sv.SupervisorIC == ViewBag.SupervisorIC.ToString()))
                                            {
                                                <tr>
                                                    <td>
                                                        <div class="d-flex px-2 py-1">
                                                            <div>
                                                                <img src="~/Content/assets/img/team-2.jpg" class="avatar avatar-sm me-3" alt="user1">
                                                            </div>
                                                            <div class="d-flex flex-column justify-content-center">
                                                                <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.Name)</h6>
                                                                <p class="text-xs text-secondary mb-0">@Html.DisplayFor(modelItem => item.Email)</p>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.MatricNo)</p>
                                                    </td>
                                                    <td>
                                                        <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.MobileNo)</p>
                                                    </td>
                                                    <td>
                                                        <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.AcademicSession)</p>
                                                    </td>
                                                    <td class="align-middle text-center">
                                                        <span class="text-secondary text-xs font-weight-bold">@Html.DisplayFor(modelItem => item.ProgramCode)</span>
                                                    </td>
                                                    <td class="align-middle">
                                                        <a href="@Url.Action("Details", "proposal", new { id = item.ProposalID })" class="btn btn-info btn-icon align-items-center btn-sm">
                                                            <span class="btn-inner--icon"><i class="fa-solid fa-file-lines" style="color: #ffffff;"></i></span>
                                                            <span class="btn-inner--text">Proposal</span>
                                                        </a>
                                                    </td>
                                                    <td></td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.Partial("_Footer")
    </main>
</body>

</html>